### ISSUE TITLE
in the readme file, read the docs link id dead

### ISSUE THREAD

**Issue by louking** [Pegase745/sqlalchemy-datatables#112]
Not sure if there's a plan to have more documentation, but the link to http://sqlalchemy-datatables.readthedocs.org/en/latest/ currently gives "SORRY this page does not exist yet"

Would love to see some use cases there, but I don't have enough experience to contribute.

**Comment by Pegase745** [comment]
I prefered having live examples rather than a readthedocs. I fixed the link issue in the `v2` branch, not sure that it's the kind of problem where a rtd is helpful. I may be wrong about it :)

**Comment by louking** [comment]
The examples are pretty basic. Of course I can look at code, but (for instance) ColumnDT has a pretty rich interface, and isn't represented in the examples. Yes I can look at code to see the interface, but seems like readthedocs would be almost free. (I understand nothing is truly free, though).

Right now looking to see if there's any way to drive representation of a boolean, e.g., as 'no', 'yes' or 'false', 'true'. This may be more sqlalchemy question though. I think I can use `func.if(False, 'no', 'yes')`, but would rather see docs than use trial and error.

**Comment by tdamsma** [comment]
You are right that the ColumnDT is just a wrapper around a sqlalchemy query. So you can do whatever sqlalchemy supports, and that is a lot. Describing that is really outside the scope this little extension. Just make sure the query returns something that is serialisable, as e.g. string.
