### ISSUE TITLE
Execute function on ColumnDT result?

### ISSUE THREAD

**Issue by eddieparker** [Pegase745/sqlalchemy-datatables#115]
I couldn't find the docs mentioned in the front page (404'd), so apologies if this is covered somewhere.

I have a column that has a JSON associative array stored, and I'd like to extract known keys from it as part of the ColumnDT call.  Is there a way to do this in the ColumnDT call so as to make sorting/filtering/etc work?

**Comment by Pegase745** [comment]
Could you plug a test example to see please ? Now that I revamped the examples on master branch, it should be easier to share those toughts

**Comment by tdamsma** [comment]
You can use sqlalchemy to extract nested jsons, just treat them like a dict

`CulumnDT(Model.jsonbfield["mykey"])`
