### ISSUE TITLE
pip doesn't provide the datatables folder and __init__.py file?

### ISSUE THREAD

**Issue by siccovansas** [Pegase745/sqlalchemy-datatables#116]
I updated to 2.0.0, but since then I can't `import datatables` as the module is not found. Looking at the `dist-packages` folder and on the [pip website](https://pypi.org/project/sqlalchemy-datatables/2.0.0/#files) it seems that the `datatables` folder containing `__init__.py` is not packaged with 2.0.0?

**Comment by Pegase745** [comment]
Fixed in `2.0.1`. Sorry for that !
