### ISSUE TITLE
model object is fetched with datatables

### ISSUE THREAD

**Issue by sachinwhiteman7** [Pegase745/sqlalchemy-datatables#125]

**Comment by Pegase745** [comment]
@sachinwhiteman7 does your issue seem readable to you ? 

Please don't use the title section in order to describe your issue.

**Comment by sachinwhiteman7** [comment]
@Pegase745 
i'm trying to fetch a table using datatables, i have defined three columns (id, phone and status ), but i'm getting a result like this, [(<Block 11>, 11, '7735353545', 'blocked')] first element is a model object, how can i remove that

**Comment by sachinwhiteman7** [comment]
my file looks like this,

columns = [ColumnDT(Block.id),
               ColumnDT(Block.phonenumber),
               ColumnDT(Block.status),
               ]
query = Block.query.filter()
row_table = DataTables(request.args, query, columns)
return jsonify(row_table.output_result())

**Comment by sachinwhiteman7** [comment]
and i'm getting this error

row_table = DataTables(request.args, query, columns)
    # print(query.all())
    # returns what is needed by DataTable
    return jsonify(row_table.output_result())

**Comment by sachinwhiteman7** [comment]
it worked when i changed to query = db.session.query().select_from(Block).filter()
