### ISSUE TITLE
Not compatible with the new version DataTables

### ISSUE THREAD

**Issue by pistatium** [Pegase745/sqlalchemy-datatables#19]
Specification of the API has changed in the new version of Datatable(1.10+)

https://datatables.net/manual/server-side

**Comment by ashl1** [comment]
What decision we make about backward compatibility to older DT 1.9- ?
DT itself [has the backward compatibility] (http://datatables.net/manual/roadmap#Backwards-compatibility) for all 1.x series, so it will be a good reason to provide it here.

**Comment by Pegase745** [comment]
It is important for us to keep it, yes !
