### ISSUE TITLE
Individual column search option

### ISSUE THREAD

**Issue by ashl1** [Pegase745/sqlalchemy-datatables#21]
Could you explainn the search_like option for columns? As writed in datatables.py:47 the type of this argument is string, but in code (datatables.py:213) it is only checked for boolean.
Is the argument 'search_like' really boolean type? Or may code haven't yet completed with that feature?

**Comment by Pegase745** [comment]
True to that, thanks for the heads up. I guess there's something missing, because the search_like is not used anywhere.
I'll see into that when I have time, or don't hesitate to PR

**Comment by ashl1** [comment]
As I understand the 'search_like' should be like used in [datatables.py:213] (https://github.com/Pegase745/sqlalchemy-datatables/blob/master/datatables/datatables.py#L215). It can  usefull if you want to add something to the standart LIKE behavior and don't think this is required.
Three solutions are possible:
* change to the boolean type and use 'True' by default just like the global search option
* change the default value to used in code now: "'%%%s%%'" and parse it to substitute by the search value
* change the type to callable or lambda with search argument which returned the result string for LIKE operation

I suggest the first solution before the real use case will become.
What do you think about?

**Comment by Pegase745** [comment]
Yes, the first solution is ok by me for now too

**Comment by Pegase745** [comment]
Nevertheless please keep in mind that the library will change in 0.2.0 because of its refactoring for it to include unit tests and DT 1.10.x compatibility

**Comment by ashl1** [comment]
Do you have any code changes now? Because I'm almost finished basic support DT 1.10.x (only transocding arguments, not implement all features).
If you has, could you publish the branch to git to use or fork it?

**Comment by Pegase745** [comment]
For the DT 1.10, i'll make a new branch. Please do the PR on it in order to be clean  ;-)
