### ISSUE TITLE
The filtering method is wrong

### ISSUE THREAD

**Issue by ashl1** [Pegase745/sqlalchemy-datatables#22]
Might the datatables.py:209 has the wrong test for the search request parameter? In current version no data is displayed, filtered by column search with empty string.
The request has always contained the 'sSearch_i' parameters with empty string. The check now test it in according to 'None' but the result is always 'not None'.
The code introduced by @tdamsma in the commit 3a99611a4b19258b6f78dc0125df7e1d1dfe8149.

I suggest to use the implicit check: "if search_value2:"

**Comment by Pegase745** [comment]
You pasted the bad commit hash

**Comment by ashl1** [comment]
Sorry, use my fork commit HASH. update it in the topic, please check again

**Comment by Pegase745** [comment]
What version of jQuery Datatables are you using ?

**Comment by ashl1** [comment]
I test it with both 1.9.0 (change the [home.pt:10] (https://github.com/Pegase745/sqlalchemy-datatables/blob/master/test-project/testproject/templates/home.pt#L10)) and 1.10.0 with test-project
