### ISSUE TITLE
pip install doesn't work for version 0.1.7

### ISSUE THREAD

**Issue by d9k** [Pegase745/sqlalchemy-datatables#28]
I try to install
`pip install --allow-all-external --pre sqlalchemy-datatables==0.1.7`
and I receive `Could not find a version that satisfies the requirement sqlalchemy-datatables==0.1.7 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6)` error

@inklesspen at the pyramid irc conference adviced me just do `pip install https://github.com/Pegase745/sqlalchemy-datatables/archive/v0.1.7.zip` but this is a temporary solution which complicates deployment of projects depending on your module.

**Comment by Pegase745** [comment]
I understand your concern, I didn't finish testing the 0.1.7 but I'll publish it on Pypi asap.

Thanks for the feedback

**Comment by d9k** [comment]
@Pegase745, but https://pypi.python.org/pypi/sqlalchemy-datatables says that current version is 0.1.7. It's confusing and frustrates when installation of new version through pip fails. Would't it be better if package description on pypi would contain note that the last available version is 0.1.6 and 0.1.7 could be downloaded from github only?

**Comment by d9k** [comment]
@Pegase745, also there must be a way to use the `pip`'s `--pre` flag feature:

`--pre  Include pre-release and development versions. By default, pip only finds stable versions.`

**Comment by Pegase745** [comment]
Done, https://pypi.python.org/pypi/sqlalchemy-datatables/0.1.7

**Comment by d9k** [comment]
Thank you so much!
