### ISSUE TITLE
Table name ans search functionality errors?

### ISSUE THREAD

**Issue by luciman** [Pegase745/sqlalchemy-datatables#29]
Hi,

I tried using your code in a flask sqlalchemy/postgresql setup in python 3.4 and in order to function I had change starting with row287:
```
           sort_name = '%s.%s' % (tablename, sort_name)
```           
replaced with
```
           sort_name = '"%s".%s' % (tablename, sort_name)
```
as I was getting postgresql syntax errors regarding the sorting table name.

Also, in order to have a functional search function I changed:
from row225:
```
                if condition is not None:
                    condition = and_(condition, and_(*conditions))
                else:
                    condition = and_(*conditions)
```
with
```
                if condition is not None:
                    condition = or_(condition, or_(*conditions))
                else:
                    condition = or_(*conditions)
```
     
Do you think there was another problem on my side or should I make a pull request?
Thanks for your nice repo.

**Comment by Pegase745** [comment]
Thanks for your feedback. 
I'll try your code, and keep you posted asap.

**Comment by Pegase745** [comment]
could I ask what version of DataTables were you using ?

**Comment by luciman** [comment]
``1.10.2``
I was using your preview pyramid example and if I remove the bottom search (column based, ``<tfoot>`` tag) the top search doesn't function without the above modifications (I realized later the culprit).
Thanks a lot!

**Comment by Pegase745** [comment]
:+1:
