### ISSUE TITLE
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00906: missing left parenthesis

### ISSUE THREAD

**Issue by okyere** [Pegase745/sqlalchemy-datatables#31]
Thanks for your package. I'm using it with flask and I'm getting the message in the title with this setup / configuration.

This is my flask view function:
```python
from sqlalchemy.orm import mapper

@theapp.route('/preview')
def preview():

    columns = []
    columns.append(ColumnDT('part_no'))
    columns.append(ColumnDT('part_nm'))
    columns.append(ColumnDT('material_spec'))
    columns.append(ColumnDT('thickness'))

    m = db.MetaData()
    ff = db.Table('fabs_features', m, autoload = True, autoload_with = db.engine)

    class Fabsfeatures(object):
        def __init__(self, part_no, part_nm, material_spec, thickness):
            self.part_no = part_no
            self.part_nm = part_nm
            self.material_spec = material_spec
            self.thickness = thickness

    mapper(Fabsfeatures, ff)

    qry = db.session.query(Fabsfeatures)

    rowTable = DataTables(request.args, Fabsfeatures, qry, columns)
    return jsonify(rowTable.output_result())
```

index.html
```html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('.static', filename='jquery.dataTables.min.css')}}">
{{super()}}
{% endblock %}

{% block scripts %}
  {{super()}}
  <script src="{{url_for('.static', filename='jquery.dataTables.min.js')}}"> </script>
  <script type="text/javascript">
        $(document).ready(function() {
          $('#previewTable').DataTable( {
          "processing": true,
          "serverSide": true,
          "ajax": "{{ url_for('preview') }}"
          });
      });
  </script>
{% endblock %}

{% block content %}
<div class="container">
    <h3>Index Page</h3>
    <table id="previewTable" class="display" cellspacing="0" width="50%">

      <thead>
                <tr>
                    <th>part_no</th>
                    <th>part_nm</th>
                    <th>material_spec</th>
                    <th>thickness</th>
                </tr>
      </thead>
      <tbody>
      </tbody>

    </table>

</div>
{% endblock %}
```

With this setup, the ajax request fails with a 500 response. In the response body, the stack trace is:

```bash
Traceback (most recent call last):
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\okyernb\pythonprojects\datatables\app\views.py", line 51, in preview
    rowTable = DataTables(request.args, Fabsfeatures, qry, columns)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\datatables\__init__.py", line 101, in __init__
    self.run()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\datatables\__init__.py", line 152, in run
    self.filtering()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\datatables\__init__.py", line 265, in filtering
    self.cardinality_filtered = self.query.count()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\orm\query.py", line 2790, in count
    return self.from_self(col).scalar()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\orm\query.py", line 2559, in scalar
    ret = self.one()
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\orm\query.py", line 2528, in one
    ret = list(self)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\orm\query.py", line 2571, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\orm\query.py", line 2586, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\util\compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\util\compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Users\okyernb\pythonprojects\datatables\env\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00906: missing left parenthesis
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT fabs_features.id AS fabs_features_id, fabs_features.part_no AS fabs_features_part_no, fabs_features.part_nm AS fabs_features_part_nm, fabs_features.material_spec AS fabs_features_material_s_1, fabs_features.thickness AS fabs_features_thickness \nFROM fabs_features \nWHERE lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_nm AS VARCHAR2)) LIKE lower(:param_2) AND lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_nm AS VARCHAR2)) LIKE lower(:param_2) AND lower(CAST(fabs_features.material_spec AS VARCHAR2)) LIKE lower(:param_3) AND lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_nm AS VARCHAR2)) LIKE lower(:param_2) AND lower(CAST(fabs_features.material_spec AS VARCHAR2)) LIKE lower(:param_3) AND lower(CAST(fabs_features.thickness AS VARCHAR2)) LIKE lower(:param_4)) anon_1'] [parameters: {'param_3': '%%', 'param_1': '%%', 'param_2': '%%', 'param_4': '%%'}]
```

I've tried to mimic the flask example in the documentation but still this is what I get. Am I doing something wrong or this is a bug in the library? Thank you.

**Comment by Pegase745** [comment]
ORA-00906 suggests that you have a problem in your database model. But you're on autoload. Could you print the datatabse sql query please ?

**Comment by okyere** [comment]
Sorry, I thought I copied and pasted the stack trace which is part of the 500 response. Anyway, here:



I think the query that's causing the problem is above.

**Comment by Pegase745** [comment]
Your stacktrace was hidden in your first comment. Try to think about highlighting when pasting code, please.

Anyway your problem is clearly linked to sqlalchemy and Oracle. You need to specify a size for the VARCHAR2 data type (e.g: VARCHAR2(40)). Because you are using autoload, sqlalchemy is mapping with your already existing schema.

I would prefer that you rewrite your table model in sqlalchemy and defining existing columns, instead of using autoload. That way you won't have any of these problems.

**Comment by okyere** [comment]
Hmm. Are you suggesting that using autoload when doing reflection does not get the size of the columns? I thought reflection creates a Table object as if hand-constructed in Python. So I'll assume it gets the columns and their sizes, etc. I'm still new to sqlachemy and all this so please enlighten me.

**Comment by Pegase745** [comment]
Just try it for yourself, and you'll see

**Comment by okyere** [comment]
Ok. This is my new view function. The table reflection code has changed. Is that what you meant? Because I'm still getting the same error.

#######################################
@theapp.route('/preview')
def preview():

    columns = []
    columns.append(ColumnDT('part_no'))
    columns.append(ColumnDT('part_nm'))
    columns.append(ColumnDT('material_spec'))
    columns.append(ColumnDT('thickness'))

    m = db.MetaData()
    #ff = db.Table('fabs_features', m, autoload = True, autoload_with = db.engine)

    ff = db.Table('fabs_features', m, db.Column('id', db.Integer, primary_key=True), db.Column('part_no', db.String(255)), db.Column('part_nm', db.String(255)), db.Column('material_spec', db.String(255)), db.Column('thickness', db.Numeric(20)))

    class Fabsfeatures(object):
        def __init__(self, part_no, part_nm, material_spec, thickness):
            self.part_no = part_no
            self.part_nm = part_nm
            self.material_spec = material_spec
            self.thickness = thickness

    mapper(Fabsfeatures, ff)

    qry = db.session.query(Fabsfeatures)

    rowTable = DataTables(request.args, Fabsfeatures, qry, columns)
    return jsonify(rowTable.output_result())
#######################################

**Comment by Pegase745** [comment]
```python
from sqlalchemy.dialects.oracle import VARCHAR2
```
Try replacing String with that

**Comment by okyere** [comment]
Ok. I included the import above. Then the reflection code is now:

ff = db.Table('fabs_features', m, db.Column('id', db.Integer, primary_key=True), db.Column('part_no', db.VARCHAR2(255)), db.Column('part_nm', db.VARCHAR2(255)), db.Column('material_spec', db.VARCHAR2(255)), db.Column('thickness', db.Numeric(20)))


I get error with this in stack trace:
  File "C:\Users\okyernb\pythonprojects\datatables\app\views.py", line 40, in preview
    ff = db.Table('fabs_features', m, db.Column('id', db.Integer, primary_key=True), db.Column('part_no', db.VARCHAR2(255)), db.Column('part_nm', db.VARCHAR2(255)), db.Column('material_spec', db.VARCHAR2(255)), db.Column('thickness', db.Numeric(20)))
AttributeError: 'SQLAlchemy' object has no attribute 'VARCHAR2'

**Comment by Pegase745** [comment]
it's ```db.dialects.oracle.VARCHAR2``` or if you import what's above, only VARCHAR2. 

But in your stacktrace you import db.VARCHAR2 and I remind you that db == sqlalchemy, so it's a bad import

**Comment by okyere** [comment]
my import is:  from sqlalchemy.dialects.oracle import VARCHAR2

now the code is: 
ff = db.Table('fabs_features', m, db.Column('id', db.Integer, primary_key=True), db.Column('part_no', VARCHAR2(255)), db.Column('part_nm', VARCHAR2(255)), db.Column('material_spec', VARCHAR2(255)), db.Column('thickness', db.Numeric(20)))


Last line of stacktrace:

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00906: missing left parenthesis
 [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT fabs_features.id AS fabs_features_id, fabs_features.part_no AS fabs_features_part_no, fabs_features.part_nm AS fabs_features_part_nm, fabs_features.material_spec AS fabs_features_material_s_1, fabs_features.thickness AS fabs_features_thickness \nFROM fabs_features \nWHERE lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_nm AS VARCHAR2)) LIKE lower(:param_2) AND lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_nm AS VARCHAR2)) LIKE lower(:param_2) AND lower(CAST(fabs_features.material_spec AS VARCHAR2)) LIKE lower(:param_3) AND lower(CAST(fabs_features.part_no AS VARCHAR2)) LIKE lower(:param_1) AND lower(CAST(fabs_features.part_nm AS VARCHAR2)) LIKE lower(:param_2) AND lower(CAST(fabs_features.material_spec AS VARCHAR2)) LIKE lower(:param_3) AND lower(CAST(fabs_features.thickness AS VARCHAR2)) LIKE lower(:param_4)) anon_1'] [parameters: {'param_4': '%%', 'param_1': '%%', 'param_2': '%%', 'param_3': '%%'}]

**Comment by okyere** [comment]
So I decided to take the whole reflection factor out to see and just define a regular model mapped to that table as: 

########################
@theapp.route('/preview')
def preview():

    columns = []
    columns.append(ColumnDT('part_no'))
    columns.append(ColumnDT('part_nm'))
    columns.append(ColumnDT('material_spec'))
    columns.append(ColumnDT('thickness'))

    class Fabsfeatures(db.Model):
        __tablename__ = 'fabs_features'

        id = db.Column(db.Integer, primary_key = True)
        part_no = db.Column(db.String(120))
        part_nm = db.Column(db.String(120))
        material_spec = db.Column(db.String(120))
        thickness = db.Column(db.Numeric(20))

    qry = db.session.query(Fabsfeatures)

    rowTable = DataTables(request.args, Fabsfeatures, qry, columns)
    return jsonify(rowTable.output_result())
#######################

The code compiles fine. But I'm still getting the sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00906: missing left parenthesis error message. This tells me that the reflect is/was not the cause of all these issues. Practically, this resembles the flask example in your tutorial almost exactly. Maybe the only difference may be that I'm using Oracle. If you spot something different, let me know.

**Comment by Pegase745** [comment]
It is for sure something related to sqlalchemy and oracle, rather than my
lib. Sorry that I couldn't have helped more. Maybe you'll be better off
posting your issue on stackoverflow or on sqlalchemy's repo.

**Comment by obenshaindw** [comment]
@okyere I experienced the same issue when trying to get a working example set up with Oracle (via cx_Oracle).  I was able to identify an issue in the datatables package and implement a work around.  There are three places in \__init\__.py from the datatables package where the SQLAlchemy cast function is called:
[Line 271](https://github.com/Pegase745/sqlalchemy-datatables/blob/master/datatables/__init__.py#L271)
[Line 284](https://github.com/Pegase745/sqlalchemy-datatables/blob/master/datatables/__init__.py#L284)
[Line 288](https://github.com/Pegase745/sqlalchemy-datatables/blob/master/datatables/__init__.py#L288)

Each time, the cast expression is being called with a String type without specifying a length which produces a SQL CAST statement to VARCHAR2 without a size, which is invalid for Oracle and generates an ORA-00906 error.  I did some testing and if you call the cast expression directly and pass in a String type with a length, the SQL statement casts to a VARCHAR2 of that specified length.

I was able to work around the issue by changing the following in datatables.\__init__.py: 
`get_attr(sqla_obj, column_name), String)`
in the three places where it occurs to:
`get_attr(sqla_obj, column_name), String(get_attr(sqla_obj, column_name).type.length))`

Column filtering now works without generating the error and the SQL being produced casts to a VARCHAR2 with length matching my db.Model definition.  This should always cause the cast to use the size of the column represented by the model, which might include a model that is autoloaded (but I haven't tested it).

@Pegase745 I could create a pull request if interested.

**Comment by Pegase745** [comment]
Nice one !
I would be happy to see your pull request David. Must just be sure that it
will still works with other DB types.
Thanks

**Comment by okyere** [comment]
@obenshaindw excellent find. Oracle is a special cat and I'm glad you found this out. I was wasn't able to use this lib for the project because of this. I hope He can merge your changes to fix this issue. I'll test it out later this week.

**Comment by obenshaindw** [comment]
@Pegase745 the Travis-CI build fails because I naively assumed the SQLAlchemy objects to have a length attribute, which for some types they do not. We're always casting to a String type in datatables.__init__.py, so for the oracle dialect we always need to provide a length to get valid DDL if we're casting to a string.

We could implement a try with except on AttributeError and assign an arbitrary size (i.e., maximum length for types that don't have a class with length attribute).

>try:
>    conditions.append(cast(
>        get_attr(sqla_obj, column_name), String(get_attr(sqla_obj, column_name).type.length))
>        .ilike('%%%s%%' % searchValue))
>
>except AttributeError:
>    conditions.append(cast(
>        get_attr(sqla_obj, column_name), String)
>        .ilike('%%%s%%' % searchValue))`

What are your thoughts?

**Comment by okyere** [comment]
Instead of try/except, what about using an if statement to handle the
special case for Oracle? I'm a novice so pardon me if my suggestion is not
a good practice.

**Comment by hangarlabs-app** [comment]
2016 called, and it wants its issue fixed. So here’s a solution to finally bring it up. All you need to do is to copy&paste the method **_apply_search()** from the ModelView into the class to admin the Oracle model that inherites from ModelView in order to replace the UNICODE argument with the VARCHAR2(255) in the two lines that makes the cast is applied.

PD: You don't have to copy it for each class either, you can create an abstract class that inherits from ModelView (maybe as MyAdminModel) and all the other classes for your models inherits from it.

![{B0708615-E20C-4B8C-8905-D122E632FEE4}](https://github.com/user-attachments/assets/005ba480-b11a-4797-a0bc-647dc6f9284c)
```

from flask_admin.contrib.sqla import ModelView
from sqlalchemy import or_
from sqlalchemy.sql.expression import cast
from sqlalchemy.dialects.oracle import VARCHAR2
from flask_admin.contrib.sqla import tools


# Custom ModelView

class ProfileModelView(ModelView):

    # Specify the columns to make searchable
    column_searchable_list = ['fitbank_id', 'username', 'email', 'first_name', 'last_name', 'legal_name', 'title', 'department_code', 'department_name']

    def _apply_search(self, query, count_query, joins, count_joins, search):
        """ Apply search to a query. """
        terms = search.split(' ')
        for term in terms:
            if not term:
                continue
            stmt = tools.parse_like_term(term)
            filter_stmt = []
            count_filter_stmt = []

            for field, path in self._search_fields:
                query, joins, alias = self._apply_path_joins(query, joins, path, inner_join=False)
                count_alias = None
                if count_query is not None:
                    count_query, count_joins, count_alias = self._apply_path_joins(count_query,
                                                                                   count_joins,
                                                                                   path,
                                                                                   inner_join=False)
                column = field if alias is None else getattr(alias, field.key)
                filter_stmt.append(cast(column, VARCHAR2(255)).ilike(stmt))
                if count_filter_stmt is not None:
                    column = field if count_alias is None else getattr(count_alias, field.key)
                    count_filter_stmt.append(cast(column, VARCHAR2(255)).ilike(stmt))
            query = query.filter(or_(*filter_stmt))
            if count_query is not None:
                count_query = count_query.filter(or_(*count_filter_stmt))
        return query, count_query, joins, count_joins

```

```
class MyModelAdmin(ModelView):
    def _apply_search(self, query, count_query, joins, count_joins, search):
        """ Inheritance Example """
        return query, count_query, joins, count_joins

class UserAdmin(MyModelAdmin):
    pass

class EmployeeAdmin(MyModelAdmin):
    pass

```
