### ISSUE TITLE
Sort expressions and user table name

### ISSUE THREAD

**Issue by slawrence** [Pegase745/sqlalchemy-datatables#34]
Hi!

Great library! I have an issue with sorts because I have a table called "user" (in retrospect maybe it could of been called "user_account" given "user"'s reserved word status). 

When the query is generated the user in the sort expression is not surrounded by quotes, for example:

    ORDER BY user.email 

Which fails and I get an error, where it really should be 

    ORDER BY "user".email 

This seems like something easily resolved - any tips? I'm not familiar with the sqlalchemy api.

Cheers,
Sean

**Comment by Pegase745** [comment]
Hello

Thanks for the feedback.

I guess there's an easy solution for you as described [here](
http://docs.sqlalchemy.org/en/latest/faq/ormconfiguration.html#how-do-i-configure-a-column-that-is-a-python-reserved-word-or-similar).


If it doesn't work out for you, I can try and push in a new example.

**Comment by slawrence** [comment]
I think in this case it's failing because user is a reserved word in PostgreSQL. Is there a way to make sure sqlalchemy escapes user in the ORDER BY clause too? It seems to escape it elsewhere. Here's an excerpt of the generated query which fails because of the user in user.email is not escaped:

    SELECT vrdb."user".id AS vrdb_user_id, vrdb."user".username  ... more stuff here ... WHERE vrdb."user".is_admin = true ORDER BY user.email ASC

**Comment by nwaomachux** [comment]
He should change his models, period. Avoid reserved words as much as
possible

**Comment by slawrence** [comment]
Yeah I know - but I think it's not possible to do at the moment.

BTW I tried this change - it works and solves the issue for me: https://github.com/slawrence/sqlalchemy-datatables/commit/47ddeadf7c7a125b4d2a258f04f8a5539e6e200d

**Comment by Pegase745** [comment]
I agree that it's best to stay away from reserved words, but great news that you found a way to solve it easily !

**Comment by tdamsma** [comment]
This is why sqlalchemy-datatables should rely on SQLAlchemy to translate python code to SQL queries, as it takes care of a lot of edgecases. This code just feels wrong:

            sort_name = '"%s".%s' % (tablename, sort_name)
            self.query = self.query.order_by(
                asc(text(sort_name)) if sort.dir == 'asc' else desc(
                    text(sort_name)))
