### ISSUE TITLE
Unable to sort by hybrid properties

### ISSUE THREAD

**Issue by patrickyan** [Pegase745/sqlalchemy-datatables#36]
I have a basic setup

```
    columns = []
    columns.append(ColumnDT('id'))
    columns.append(ColumnDT('name'))
    columns.append(ColumnDT('address'))
    columns.append(ColumnDT('child.date'))
    columns.append(ColumnDT('created_at'))
```

When trying to sort on `name` or `address` which is a hybrid property, I get 

```
OperationalError: (OperationalError) (1054, "Unknown column 'obj.address' in 'order clause'")
```

How the hybrid property is defined

```
    @hybrid_property
    def name(self):
        return utils.join([self.first_name, self.last_name])

    @name.expression
    def name(cls):
        return cls.first_name + ' ' + ls.last_name
```

**Comment by Pegase745** [comment]
Could you possibly create an example [here](https://github.com/Pegase745/sqlalchemy-datatables/tree/master/examples) in a branch, so that I can look at it from the same point of view as you?

**Comment by ufoczek** [comment]
Example created

**Comment by tdamsma** [comment]
@Pegase745, think this can be closed as it should be solved now

**Comment by Pegase745** [comment]
@tdamsma I didn't rebase his example onto the latest code evolution in order ton confirm that yet
