### ISSUE TITLE
use regex for data retrieval?

### ISSUE THREAD

**Issue by louking** [Pegase745/sqlalchemy-datatables#40]
as of sqlalchemy-datatables 0.2.1 queries from multi-select field type are not supported (e.g., from yadcf, see http://stackoverflow.com/questions/32855901/yadcf-with-select2-puts-empty-selected-option)

the actual "non-support" is for columns where regex is True, coming from dataTables client

regex is supported by sqlalchemy for some dialects, e.g., see http://stackoverflow.com/questions/27228635/how-can-a-sqlalchemy-query-use-mysqls-regexp-operator

not sure if it would be sufficient to support | (OR) operator through hard coding, which will allow multi-selects

for my current need, hard coded support of OR operator, or mysql support of regex would be sufficient, but that is not a complete solution

**Comment by louking** [comment]
I'm working on a pull request. 

But see http://datatables.net/forums/discussion/33699/search-regex-sub-expression-error

**Comment by Pegase745** [comment]
Sorry for not having the time before now to look into that, but go on with
the pull request and will help asap! Thanks

**Comment by louking** [comment]
Thanks. I have two pull requests in now, for #38 and this issue

Not sure how much you will like this one because it makes use of special features provided by mysql and postgresql dialects

Also not handled well is invalid regex from table search box, query outstanding to dataTables. I can continue working on this aspect or maybe it's a dataTables change depending on Allan's answer.
