### ISSUE TITLE
clean_regex fails with int and bool values

### ISSUE THREAD

**Issue by tissieres** [Pegase745/sqlalchemy-datatables#51]
Hi,
The clean_regex function added in the last commit expects only a str. But searchValue can be either a bool, a int or a str. A naive fix would be 

```
if isinstance(searchValue, str):
  regex = clean_regex(searchValue)
else:
  regex = searchValue
```

**Comment by Pegase745** [comment]
Thanks !

**Comment by louking** [comment]
Sorry about that -- I'm not clear what would cause datatables to send int or bool, but I think the fix looks fine in any case.

**Comment by tissieres** [comment]
The `prepare_arguments` function tries to convert the value it gets from the request to a int, a bool before keeping it as a str.

**Comment by tdamsma** [comment]
Closing this as it doesn't apply to to the current version of sqlalchemy-datatables
