### ISSUE TITLE
Data show only first record

### ISSUE THREAD

**Issue by theavuthnhel** [Pegase745/sqlalchemy-datatables#52]
Hello!

This package is very useful, but now I have one problem with data showing it's show only one first record.

Here is my script:

``` javascript
$("#data_list").dataTable({
                "serverSide": true,
                "processing": true,
                "ajax": "{{ url_for('getAppData') }}?start=1&length=1&draw=1&model=Table&fields=field_list"
            });
```

Any solution here?
Thanks in advance...

**Comment by Pegase745** [comment]
I guess it's because of you `length=1`. Why would you put hard-coded query-strings like these ?

cf https://datatables.net/reference/api/length

**Comment by theavuthnhel** [comment]
Hello!

When I try to request without `length`, `draw`, `start` it's show the error from python code.

**Comment by Pegase745** [comment]
@theavuthnhel how did you manage to get around that in the end ?
