### ISSUE TITLE
regex use case: with yadcf exact match select filters regex is garbled

### ISSUE THREAD

**Issue by louking** [Pegase745/sqlalchemy-datatables#54]
When using https://github.com/vedmack/yadcf select filter filter_match_mode = 'exact', clean_regex is escaping the beginning and ending anchors, as well as outside parenthesis within those anchors. This causes the filter not to work.

Pull request is pending, want to soak test some before release. Still have no way to write unit tests for these because of mysql requirement.

**Comment by tdamsma** [comment]
closing this as it doesn't apply to the latest version
