### ISSUE TITLE
yadcf use case: range of dates / numbers not handled

### ISSUE THREAD

**Issue by louking** [Pegase745/sqlalchemy-datatables#58]
[yadcf](https://github.com/vedmack/yadcf) provides `columns[n][search][value]` containing start-yadcf_delim-end for start, end range filtering. I need to fix this and will supply pull request tailored for yadcf, but not sure if there are other filtering add-ons out there which could also be supported.

**Comment by tdamsma** [comment]
Handling yadcf filters is supported now
