### ISSUE TITLE
When instantiating a DataTable, tables w/ tablename that need double-quotes aren't supported

### ISSUE THREAD

**Issue by kim-tran** [Pegase745/sqlalchemy-datatables#59]
I'm using a database model not created by me so I'm hesitant to change it. 
I tried with a table where the tablename is not case-sensitive and it works fine.

Modifying from the example:

**view.py**
`columns = []`
`columns.append(ColumnDT('id'))`
`query = db.session.query(Test).filter(Test.id < 100)`
`rowTable = DataTables(request.args, Test, query, columns)`

**model.py**
`class Test(Base)`
`__tablename__= 'Test'`
`id = Column(Integer, primary_key=True)`
`# columns`

I get this error:

```
ProgrammingError: (psycopg2.ProgrammingError) missing FROM-clause entry for table "test"
LINE 3: WHERE "Test".id < 100 ORDER BY Test.id ASC
```

**Comment by Pegase745** [comment]
Weird i'll look into it asap !

**Comment by kim-tran** [comment]
Skimming through the code, I spotted the problem.

https://github.com/Pegase745/sqlalchemy-datatables/blob/master/datatables/__init__.py#L441

Should be changed to:
`sort_name = '"%s".%s' % (tablename, sort_name)`

**Comment by Pegase745** [comment]
would you like to propose a pull request ?

**Comment by tdamsma** [comment]
@Pegase745, think this can be closed as it should be solved now
