### ISSUE TITLE
Querying Many-To-Many relationships

### ISSUE THREAD

**Issue by 1tm** [Pegase745/sqlalchemy-datatables#65]
Hello!

Could you please help me with many-to-many related tables?

Relation set in models:

``` python
class Asset(db.Model):
...
users = db.relationship('User', secondary=ext_vs_users, backref='extensions', lazy='dynamic')
```

Query given to datatable:

``` python
data_table = DataTables(request.args, Asset, query, columns)
```

Columns set:

``` python
columns.append(ColumnDT('number'))
columns.append(ColumnDT('location'))
columns.append(ColumnDT('display_name'))
columns.append(ColumnDT('users.uid'))
```

There can be both single and multiple users per asset. But for every row I get "None" in users.uid column. Is it possible to somehow retreive data in this case?

P.S. Thanks for a great package! :)

**Comment by tdamsma** [comment]
Could you please try and see if the recent updates would solve your issue? It should look something like this:

``` python

columns = [
    ColumnDT(Asset.number),
    ColumnDT(Asset.location),
    ColumnDT(Asset.display_name),
    ColumnDT(User.uid)]

query=session.query().select_from(Asset).join(User)
```

**Comment by tdamsma** [comment]
See also https://github.com/Pegase745/sqlalchemy-datatables/issues/83
