### ISSUE TITLE
Travis tests sometimes failing for no apparent reason

### ISSUE THREAD

**Issue by tdamsma** [Pegase745/sqlalchemy-datatables#69]
Perhaps because I added an extra test, there seems to be a race condition for the sqlite3 database where some of the tests fail due to columns existing from a previous test. Not entirely sure how to solve this, perhaps move all tests to one script. @Pegase745, if you manually ask Travis to rebuild, it will probably be ok. Perhaps this is an issue with the coveralls test runner, you could try to switch to `py.test` with `--cov` flag, perhaps that would solve it.

**Comment by Pegase745** [comment]
@tdamsma you are right it [worked](https://travis-ci.org/Pegase745/sqlalchemy-datatables/builds/181637885) !

**Comment by Pegase745** [comment]
Fixed in #73

**Comment by tdamsma** [comment]
Unfortunately using pytest hasn't completely solved this, i just saw a test for https://github.com/Pegase745/sqlalchemy-datatables/pull/75 that failed on sqlite3 non unique columns, but that worked after restarting the test

**Comment by Pegase745** [comment]
Yep just saw that too
