### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'list' - line 245

### ISSUE THREAD

**Issue by dremdem** [Pegase745/sqlalchemy-datatables#74]
Hi, 

I dowloaded latest version 1.1.0 and got the error when render the table:

  File "/home/vagrant/pycharm_proj/arp_norm/venv/lib/python2.7/site-packages/datatables/__init__.py", line 245, in output_result
    output['draw'] = str(int(self.params['draw']))
TypeError: int() argument must be a string or a number, not 'list'

**Comment by tdamsma** [comment]
Could it be the draw parameter is in the url query more than once?

**Comment by grakic** [comment]
If using Flask, you need to pass parameters as `request.args.to_dict()`. This library is using `dict()` on it, and with Werkzeug's MultiDict this creates a dictionary with lists, not elements.
