### ISSUE TITLE
Flask not working

### ISSUE THREAD

**Issue by caseydm** [Pegase745/sqlalchemy-datatables#87]
I tried to use this in a flask application but am getting a server 500 error. I noticed in the README you say 'it is currently not working with flask'. Do you have a hunch on what the problem is? Maybe there is a way I can help? I would love to get this working.

**Comment by Pegase745** [comment]
@caseydm can you please pull the `master` branch once again and follow the instructions in the README file of the `flask_tut` example ? I fixed it, and hope it works for you too

**Comment by caseydm** [comment]
@Pegase745 I figured out the error and it was not a bug like I thought. The 500 error was due to a JSON serialization issue with a datetime field. The app is working great with Flask! Thank you for developing it.

**Comment by Pegase745** [comment]
@caseydm there was a problem with the example, but great to hear that everything is ok :)
