### ISSUE TITLE
Optimized Datatable

### ISSUE THREAD

**Issue by saifraider** [Pegase745/sqlalchemy-datatables#88]
Hi,

Thank you so much. Everything is working fine. 

I had one question. If I had 10000 rows. Is it fetching and loading all rows at one time or it is optimized?

Thank you.

Best Regards,
Saif

**Comment by Pegase745** [comment]
Server side pagination is there to help. The total row count is 10000 but
you can show as much as you much per page.

**Comment by saifraider** [comment]
Thank you for the quick response.
