### ISSUE TITLE
Custom sort option

### ISSUE THREAD

**Issue by pankus** [Pegase745/sqlalchemy-datatables#99]
First of all let me say that this is not an issue, but just a question.
My case: I need to order a table throught four different db columns in order to obtain a 'natural sort', but of course if I add an order by clause to the definition of the initial query this propagates to any further attempt of sorting. 
i.e.:
`query = db.session.query().select_from(MyTable).\
     order_by(MyTable.col1, MyTable.col2, MyTable.col3, MyTable.col4)`
At a first glance it works, but at the same time it prevent any other attempt of dynamic sorting of the table.
So what I'm asking for is:
How to define a custom sort option for one of the columns? Is it possible to attache a keyword argument to the column definition in order to obtain my need?
As far as I can understand from the source code I cannot figure it out if it is possible... sorry I'm not a true programmer! 

Many thanks in advance

**Comment by tdamsma** [comment]
you should be able to define multiple sorting columns in the the javascript of datatables. I belive this supports multi column ordering
